# Copyright (c) 2026 HELIX. All rights reserved.
# HELIX Personal Intelligence OS
"""ReflexAgent manages self-improvement and behavioural rules."""

import asyncio
import logging
from typing import Any
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import text
from helix.event_bus import bus, ChatTurn
from helix.db.schema import get_session
from helix.llm_client import llm_client
from helix.config import config

logger = logging.getLogger(__name__)

class ReflexAgent:
    """Agent that reflects on conversations to extract rules."""

    def __init__(self) -> None:
        self._stop_event = asyncio.Event()
        self._tasks: list[asyncio.Task[Any]] = []
        self._turn_count = 0

        self.rules_file = Path(config.vault.index_path).expanduser() / "self" / "rules.md"
        self.rules_file.parent.mkdir(parents=True, exist_ok=True)

        bus.subscribe(ChatTurn, self._on_chat_turn)

    async def _on_chat_turn(self, event: ChatTurn) -> None:
        """Tracks chat turns and conditionally triggers reflection."""
        if event.role == "user":
            self._turn_count += 1
            if self._turn_count >= 5:
                self._turn_count = 0
                asyncio.create_task(self.reflect(event.session_id))

    async def reflect(self, session_id: str | None = None) -> None:
        """Trigger reflection loop based on recent conversation context."""
        logger.info("ReflexAgent reflection triggered.")

        try:
            # 1. Gather recent turns
            async with get_session() as session:
                result = await session.execute(
                    text("SELECT role, content FROM conversations ORDER BY timestamp DESC LIMIT 20")
                )
                rows = result.fetchall()

            if not rows:
                return

            # Reverse to chronological order
            rows = list(rows)
            rows.reverse()
            formatted_turns = "\n".join([f"{r[0].upper()}: {r[1]}" for r in rows])

            # 2. Setup Prompt
            prompt = f"""
            Review this conversation session and identify improvements.

            Session summary:
            <session>
            {formatted_turns}
            </session>

            Identify and write:
            1. Any questions the assistant answered poorly or incompletely
            2. Information the user had to repeat (suggests memory gap)
            3. User preferences revealed (communication style, topics, formats)
            4. Any tasks or commitments mentioned but not tracked

            Write improvement rules in this exact JSON format:
            {{
              "rules": [
                {{
                  "rule_text": "When user asks about X, always also check Y",
                  "rule_type": "retrieval",
                  "confidence": 0.8
                }}
              ],
              "user_preferences": ["prefers bullet points"],
              "missed_tasks": ["follow up with John by Friday"]
            }}
            """

            # 3. Call LLM
            response_text = await llm_client.generate(prompt=prompt, system="Return ONLY valid JSON.", expect_json=True)
            import re
            cleaned = re.sub(r'^```json\s*|\s*```$', '', response_text.strip())
            data = json.loads(cleaned)

            now_str = datetime.now(timezone.utc).isoformat()

            # 4. Extract and Save Rules
            rules = data.get("rules", [])
            if rules:
                async with get_session() as session:
                    for rule in rules:
                        rule_id = str(uuid.uuid4())
                        rule_text = rule.get("rule_text", "")
                        rule_type = rule.get("rule_type", "behavioural")
                        confidence = rule.get("confidence", 0.7)

                        if rule_text:
                            await session.execute(
                                text("""
                                    INSERT INTO reflex_rules (id, rule_text, rule_type, confidence, created_at)
                                    VALUES (:id, :txt, :type, :conf, :now)
                                """),
                                {"id": rule_id, "txt": rule_text, "type": rule_type, "conf": confidence, "now": now_str}
                            )
                    await session.commit()

                # Append to self/rules.md
                import aiofiles
                async with aiofiles.open(self.rules_file, "a", encoding="utf-8") as f:
                    if self.rules_file.stat().st_size == 0:
                        await f.write("# HELIX Behavioural Rules\n*Auto-generated by ReflexAgent.*\n\n")
                    for rule in rules:
                        await f.write(f"- **{rule.get('rule_type', 'Rule').capitalize()}**: {rule.get('rule_text', '')}\n")

                logger.info(f"ReflexAgent stored {len(rules)} new rules.")

        except json.JSONDecodeError:
            logger.warning("ReflexAgent failed to parse LLM JSON.")
        except Exception as e:
            logger.error(f"ReflexAgent reflection failed: {e}")

    async def run(self) -> None:
        while not self._stop_event.is_set():
            await asyncio.sleep(1.0)

    async def stop(self) -> None:
        self._stop_event.set()
        if self._tasks:
            await asyncio.gather(*self._tasks, return_exceptions=True)
        logger.info("ReflexAgent stopped.")
