"""
Module: helix/agents/wiki_agent.py
Copyright (c) 2026 HELIX. All rights reserved.

WikiAgent manages markdown knowledge pages in the vault/wiki/ directory.
It responds to FileProcessed events to update the wiki graph.
"""

import asyncio
import logging
from typing import Any
from pathlib import Path
import aiofiles

from sqlalchemy import text
from helix.event_bus import bus, FileProcessed, WikiUpdated
from helix.config import config
from helix.db.schema import get_session

logger = logging.getLogger(__name__)

class WikiAgent:
    """
    Agent that curates the vault/wiki/ markdown files.
    Listens for FileProcessed events to maintain human-readable knowledge summaries.
    """

    def __init__(self) -> None:
        self._stop_event = asyncio.Event()
        self._tasks: list[asyncio.Task[Any]] = []

        self.wiki_dir = Path(config.vault.index_path).expanduser() / "wiki"
        self.wiki_dir.mkdir(parents=True, exist_ok=True)

        bus.subscribe(FileProcessed, self._on_file_processed)

    async def _on_file_processed(self, event: FileProcessed) -> None:
        """
        Handler triggered when a new file has been successfully processed.
        Should extract knowledge and update markdown wiki pages.
        """
        try:
            file_record = event.record
            if not isinstance(file_record, dict) or "id" not in file_record:
                return

            file_id = file_record["id"]

            # Fetch the complete file metadata from SQLite
            async with get_session() as session:
                result = await session.execute(
                    text("SELECT file_name, file_path, category, summary, tags, indexed_at FROM files WHERE id = :id"),
                    {"id": file_id}
                )
                row = result.fetchone()

            if not row:
                return

            file_name, file_path, category, summary, tags_json, indexed_at = row
            category_clean = str(category).replace("/", "_").replace(" ", "_")

            # 1. Update Category Wiki Page
            cat_page_path = self.wiki_dir / f"{category_clean}.md"
            await self._append_to_wiki(cat_page_path, f"## {file_name}\n**Path:** `{file_path}`\n**Summary:** {summary}\n**Indexed:** {indexed_at}\n\n", "category")

            logger.info(f"WikiAgent updated wiki for {file_name}")

        except Exception as e:
            logger.error(f"WikiAgent failed to process file {event.record}: {e}")

    async def _append_to_wiki(self, path: Path, content: str, page_type: str) -> None:
        """Appends content to a markdown file, creating it with a header if it doesn't exist."""
        is_new = not path.exists()

        try:
            async with aiofiles.open(path, "a", encoding="utf-8") as f:
                if is_new:
                    title = path.stem.replace("_", " ")
                    await f.write(f"# {title} Knowledge Base\n*Auto-generated by HELIX WikiAgent*\n\n")
                await f.write(content)

            operation = "created" if is_new else "updated"
            bus.publish(WikiUpdated(page_path=str(path), operation=operation))
        except Exception as e:
            logger.error(f"WikiAgent failed to write to {path}: {e}")

    async def run(self) -> None:
        """Long-running coroutine for the agent's main loop."""
        while not self._stop_event.is_set():
            await asyncio.sleep(1.0)

    async def stop(self) -> None:
        """Signals the agent to exit."""
        self._stop_event.set()
        if self._tasks:
            await asyncio.gather(*self._tasks, return_exceptions=True)
        logger.info("WikiAgent stopped.")
